model:
  name: yolo11n.pt                 # 탐지 전용 체크포인트
  data_cfg: ./configs/data.yaml

train:
  imgsz: 640
  epochs: 100
  batch: 16
  device: cpu                      # GPU면 "0"
  lr0: 0.01
  mosaic: 1.0
  close_mosaic_epoch: 10
  seed: 42
  hsv: true